In [850]:
import pandas as pd

# Limpieza y Procesamiento de Datos

## 1.

In [851]:
df_jugadores = pd.read_csv("jugadores.csv") # Cargar jugadores.csv en un DataFrame
df_jugadores # Mostrar las primeras filas del DataFrame para verificar su contenido

,player_id,seleccion,numero,posicion,jugador,fecha_nac,edad,caps,goles_seleccion,club,...,keeper_performance_cspct,keeper_penalty_kicks_pkatt,keeper_penalty_kicks_pka,keeper_penalty_kicks_pksv,keeper_penalty_kicks_pkm,keeper_penalty_kicks_savepct,keeper_playing_time_90s,nat3,valor_mercado_eur,posicion_tm
0,1,Czech Republic,1,GK,Matěj Kovář,2000-05-17,26,19,0,PSV Eindhoven,...,22.6,4.0,3.0,0.0,1.0,0.0,31.0,CZE,7000000.0,Goalkeeper
1,2,Czech Republic,2,DF,David Zima,2000-11-08,25,24,1,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,4500000.0,Centre-Back
2,3,Czech Republic,3,DF,Tomáš Holeš,1993-03-31,33,40,2,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,2200000.0,Centre-Back
3,4,Czech Republic,4,DF,Robin Hranáč,2000-01-29,26,13,1,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,5500000.0,Centre-Back
4,5,Czech Republic,5,DF,Vladimír Coufal,1992-08-22,33,61,2,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,7000000.0,Right-Back
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240,1241,Panama,22,GK,Orlando Mosquera,1994-12-25,31,47,0,Al-Fayha,...,21.9,6.0,2.0,2.0,2.0,50.0,32.0,PAN,350000.0,Goalkeeper
1241,1242,Panama,23,DF,Michael Amir Murillo,1996-02-11,30,93,9,Beşiktaş,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAN,7000000.0,Right-Back
1242,1243,Panama,24,FW,Azarias Londoño,2001-06-21,24,10,0,Universidad Católica,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAN,175000.0,Centre-Forward
1243,1244,Panama,25,DF,Roderick Miller,1992-04-03,34,50,2,Turan Tovuz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175000.0,Centre-Back
1244,1245,Panama,26,DF,Jorge Gutiérrez,1998-09-01,27,18,0,Deportivo La Guaira,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325000.0,Left-Back

## 2.

### a)
Todas las selecciones tienen 26 jugadores, excepto Austria, Canadá y Jordania que tienen 25

In [852]:
df_jugadores["seleccion"].nunique() # Cuántas selecciones distintas hay

48

In [853]:
selecciones = df_jugadores.groupby("seleccion")
selecciones.size().unique() # Cuántos jugadores hay por selección

array([26, 25])

In [854]:
selecciones.size()[selecciones.size() == 25]

seleccion
Austria    25
Canada     25
Jordan     25
dtype: int64

### b)

In [855]:
df_jugadores["club"].nunique()

449

In [856]:
cantidad_clubes = df_jugadores.groupby("club").size()
cantidad_clubes[cantidad_clubes>=10].sort_values()

club
Fenerbahçe             10
Milan                  10
Real Madrid            10
PSV Eindhoven          10
Slavia Prague          10
Galatasaray            11
Liverpool              11
Borussia Dortmund      11
Atlético Madrid        12
Manchester United      12
Crystal Palace         12
Al-Hilal               12
Barcelona              15
Paris Saint-Germain    16
Arsenal                16
Bayern Munich          18
Manchester City        19
dtype: int64

### c)
El rango etario dominante en las primeras cinco selecciones del ranking FIFA es entre 24 y 30 años

In [857]:
rango_etario = lambda edad : "A" if edad < 24 else ("B" if edad <= 30 else "C")
df_jugadores["rango_etario"] = [rango_etario(edad) for edad in df_jugadores["edad"]]
df_jugadores

,player_id,seleccion,numero,posicion,jugador,fecha_nac,edad,caps,goles_seleccion,club,...,keeper_penalty_kicks_pkatt,keeper_penalty_kicks_pka,keeper_penalty_kicks_pksv,keeper_penalty_kicks_pkm,keeper_penalty_kicks_savepct,keeper_playing_time_90s,nat3,valor_mercado_eur,posicion_tm,rango_etario
0,1,Czech Republic,1,GK,Matěj Kovář,2000-05-17,26,19,0,PSV Eindhoven,...,4.0,3.0,0.0,1.0,0.0,31.0,CZE,7000000.0,Goalkeeper,B
1,2,Czech Republic,2,DF,David Zima,2000-11-08,25,24,1,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,CZE,4500000.0,Centre-Back,B
2,3,Czech Republic,3,DF,Tomáš Holeš,1993-03-31,33,40,2,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,CZE,2200000.0,Centre-Back,C
3,4,Czech Republic,4,DF,Robin Hranáč,2000-01-29,26,13,1,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,CZE,5500000.0,Centre-Back,B
4,5,Czech Republic,5,DF,Vladimír Coufal,1992-08-22,33,61,2,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,CZE,7000000.0,Right-Back,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240,1241,Panama,22,GK,Orlando Mosquera,1994-12-25,31,47,0,Al-Fayha,...,6.0,2.0,2.0,2.0,50.0,32.0,PAN,350000.0,Goalkeeper,C
1241,1242,Panama,23,DF,Michael Amir Murillo,1996-02-11,30,93,9,Beşiktaş,...,NaN,NaN,NaN,NaN,NaN,NaN,PAN,7000000.0,Right-Back,B
1242,1243,Panama,24,FW,Azarias Londoño,2001-06-21,24,10,0,Universidad Católica,...,NaN,NaN,NaN,NaN,NaN,NaN,PAN,175000.0,Centre-Forward,B
1243,1244,Panama,25,DF,Roderick Miller,1992-04-03,34,50,2,Turan Tovuz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175000.0,Centre-Back,C
1244,1245,Panama,26,DF,Jorge Gutiérrez,1998-09-01,27,18,0,Deportivo La Guaira,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325000.0,Left-Back,B

In [858]:
top_cinco_ranking_fifa = ["Argentina", "Francia", "España", "Inglaterra", "Brasil"]
df_top_cinco = df_jugadores[df_jugadores["seleccion"].isin(top_cinco_ranking_fifa)]
df_top_cinco.groupby("rango_etario").size().sort_values(ascending=False)

rango_etario
B    15
C     8
A     3
dtype: int64

## 3.
Eliminamos todas las variables del grupo playing_time_, ya que no abarcan el 60% de cobertura

In [859]:
variables = ["standard_playing_time_mp", "shooting_90s", "misc_performance_fls", "playing_time_starts_starts"]
df_variables = df_jugadores[variables]
df_variables.notna().sum()/len(df_jugadores) * 100

standard_playing_time_mp      73.975904
shooting_90s                  74.056225
misc_performance_fls          71.405622
playing_time_starts_starts    38.232932
dtype: float64

In [860]:
variables_playing_time = [col for col in df_jugadores.columns if col.startswith("playing_time_")]
df_jugadores.drop(columns=variables_playing_time, inplace=True)
df_jugadores.columns.size

82

## 4.
Las variables que estén en NAN las podemos poner en 0, ya que se basan en tiros y si el jugador no realizó ninguno cualquier ratio debería dar 0

In [861]:
variables_shooting = [col for col in df_jugadores.columns if col.startswith("shooting_")]
df_jugadores.fillna({col: 0 for col in variables_shooting}, inplace=True) # Reemplazar los valores faltantes por 0
print(df_jugadores[variables_shooting].isna().sum()) # Verificar que los valores faltantes hayan sido reemplazados

shooting_90s                    0
shooting_standard_gls           0
shooting_standard_sh            0
shooting_standard_sot           0
shooting_standard_sotpct        0
shooting_standard_sh_per_90     0
shooting_standard_sot_per_90    0
shooting_standard_g_per_sh      0
shooting_standard_g_per_sot     0
shooting_standard_pk            0
shooting_standard_pkatt         0
dtype: int64

In [862]:
col_ratios = ["shooting_standard_sh", "shooting_standard_sot","shooting_standard_sotpct","shooting_standard_sh_per_90","shooting_standard_sot_per_90"]
df_jugadores[col_ratios].isna().sum()

shooting_standard_sh            0
shooting_standard_sot           0
shooting_standard_sotpct        0
shooting_standard_sh_per_90     0
shooting_standard_sot_per_90    0
dtype: int64

In [863]:
df_jugadores[col_ratios] = df_jugadores[col_ratios].fillna(0)
df_jugadores

,player_id,seleccion,numero,posicion,jugador,fecha_nac,edad,caps,goles_seleccion,club,...,keeper_penalty_kicks_pkatt,keeper_penalty_kicks_pka,keeper_penalty_kicks_pksv,keeper_penalty_kicks_pkm,keeper_penalty_kicks_savepct,keeper_playing_time_90s,nat3,valor_mercado_eur,posicion_tm,rango_etario
0,1,Czech Republic,1,GK,Matěj Kovář,2000-05-17,26,19,0,PSV Eindhoven,...,4.0,3.0,0.0,1.0,0.0,31.0,CZE,7000000.0,Goalkeeper,B
1,2,Czech Republic,2,DF,David Zima,2000-11-08,25,24,1,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,CZE,4500000.0,Centre-Back,B
2,3,Czech Republic,3,DF,Tomáš Holeš,1993-03-31,33,40,2,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,CZE,2200000.0,Centre-Back,C
3,4,Czech Republic,4,DF,Robin Hranáč,2000-01-29,26,13,1,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,CZE,5500000.0,Centre-Back,B
4,5,Czech Republic,5,DF,Vladimír Coufal,1992-08-22,33,61,2,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,CZE,7000000.0,Right-Back,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240,1241,Panama,22,GK,Orlando Mosquera,1994-12-25,31,47,0,Al-Fayha,...,6.0,2.0,2.0,2.0,50.0,32.0,PAN,350000.0,Goalkeeper,C
1241,1242,Panama,23,DF,Michael Amir Murillo,1996-02-11,30,93,9,Beşiktaş,...,NaN,NaN,NaN,NaN,NaN,NaN,PAN,7000000.0,Right-Back,B
1242,1243,Panama,24,FW,Azarias Londoño,2001-06-21,24,10,0,Universidad Católica,...,NaN,NaN,NaN,NaN,NaN,NaN,PAN,175000.0,Centre-Forward,B
1243,1244,Panama,25,DF,Roderick Miller,1992-04-03,34,50,2,Turan Tovuz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175000.0,Centre-Back,C
1244,1245,Panama,26,DF,Jorge Gutiérrez,1998-09-01,27,18,0,Deportivo La Guaira,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325000.0,Left-Back,B

## 5.
La baja cobertura de las variables keeper_ se debe a que solo aplica a aquellos jugadores que ocupen esta posición. Esto se puede arreglar reemplazando los NA por 0 excepto aquellos donde exista alguna variable similar en otro grupo (como partidos como titular o minutos jugados).

In [864]:
copia = df_jugadores.copy() # Hago una copia del DataFrame para no modificar el original
variables_keeper = [col for col in copia.columns if col.startswith("keeper_")]
copia.fillna({col: 0 for col in variables_keeper}, inplace=True) # Reemplazar los valores faltantes por 0
print(copia[variables_keeper].isna().sum()) # Verificar que los valores faltantes hayan sido reemplazados

keeper_playing_time_mp          0
keeper_playing_time_starts      0
keeper_playing_time_min         0
keeper_90s                      0
keeper_performance_ga           0
keeper_performance_ga90         0
keeper_performance_sota         0
keeper_performance_saves        0
keeper_performance_savepct      0
keeper_performance_w            0
keeper_performance_d            0
keeper_performance_l            0
keeper_performance_cs           0
keeper_performance_cspct        0
keeper_penalty_kicks_pkatt      0
keeper_penalty_kicks_pka        0
keeper_penalty_kicks_pksv       0
keeper_penalty_kicks_pkm        0
keeper_penalty_kicks_savepct    0
keeper_playing_time_90s         0
dtype: int64

## 6.

In [865]:
porcentajes = (df_jugadores.notna().sum() / len(df_jugadores) * 100).sort_values() # Porcentaje de valores no faltantes por variable
porcentajes[porcentajes < 60] # Variables con menos del 60% de valores no faltantes

misc_performance_pkwon          0.000000
misc_performance_pkcon          0.000000
keeper_90s                      2.811245
keeper_playing_time_90s         4.417671
keeper_penalty_kicks_savepct    6.184739
keeper_performance_savepct      6.666667
keeper_performance_sota         6.746988
keeper_performance_saves        6.746988
keeper_performance_cspct        7.148594
keeper_performance_w            7.228916
keeper_performance_d            7.228916
keeper_playing_time_mp          7.228916
keeper_performance_ga           7.228916
keeper_playing_time_starts      7.228916
keeper_playing_time_min         7.228916
keeper_performance_ga90         7.228916
keeper_penalty_kicks_pka        7.228916
keeper_penalty_kicks_pkatt      7.228916
keeper_penalty_kicks_pksv       7.228916
keeper_penalty_kicks_pkm        7.228916
keeper_performance_l            7.228916
keeper_performance_cs           7.228916
dtype: float64

In [866]:
# Elimino las variables misc_performance_pkwon, misc_performance_pkcon, y las de keeper_ ya que tienen < 60% de cobertura.
df_jugadores_limpia = df_jugadores.drop(columns=["misc_performance_pkwon", "misc_performance_pkcon"] + variables_keeper)
df_jugadores_limpia.reset_index(drop=True, inplace=True) # Reiniciar el índice del DataFrame
df_jugadores_limpia.columns.size

60

In [867]:
df_jugadores_limpia.isna().sum(axis=1).value_counts().sort_index() # Cantidad de filas valores faltantes

0     873
1       8
2       7
6      33
19      1
30      1
32    294
33      4
34     24
Name: count, dtype: int64

In [868]:
df_jugadores_limpia.drop(df_jugadores_limpia[df_jugadores_limpia.isna().sum(axis=1)>30].index, inplace=True) # Elimino filas con más de 30 valores faltantes (mas de la mitad de las variables)
df_jugadores_limpia.reset_index(drop=True, inplace=True) # Reseteo el índice del DataFrame
df_jugadores_limpia

,player_id,seleccion,numero,posicion,jugador,fecha_nac,edad,caps,goles_seleccion,club,...,misc_performance_fld,misc_performance_off,misc_performance_crs,misc_performance_int,misc_performance_tklw,misc_performance_og,nat3,valor_mercado_eur,posicion_tm,rango_etario
0,1,Czech Republic,1,GK,Matěj Kovář,2000-05-17,26,19,0,PSV Eindhoven,...,5.0,0.0,0.0,1.0,0.0,0.0,CZE,7000000.0,Goalkeeper,B
1,2,Czech Republic,2,DF,David Zima,2000-11-08,25,24,1,Slavia Prague,...,22.0,0.0,4.0,40.0,17.0,0.0,CZE,4500000.0,Centre-Back,B
2,3,Czech Republic,3,DF,Tomáš Holeš,1993-03-31,33,40,2,Slavia Prague,...,28.0,1.0,22.0,44.0,24.0,0.0,CZE,2200000.0,Centre-Back,C
3,4,Czech Republic,4,DF,Robin Hranáč,2000-01-29,26,13,1,TSG Hoffenheim,...,10.0,0.0,6.0,20.0,15.0,0.0,CZE,5500000.0,Centre-Back,B
4,5,Czech Republic,5,DF,Vladimír Coufal,1992-08-22,33,61,2,TSG Hoffenheim,...,42.0,1.0,209.0,39.0,35.0,0.0,CZE,7000000.0,Right-Back,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,1239,Panama,20,MF,Aníbal Godoy,1990-02-10,36,159,4,San Diego FC,...,37.0,0.0,3.0,16.0,14.0,0.0,PAN,200000.0,Defensive Midfield,C
919,1240,Panama,21,MF,César Yanis,1996-01-28,30,56,5,Cobresal,...,36.0,4.0,39.0,24.0,13.0,0.0,PAN,250000.0,Right Winger,B
920,1241,Panama,22,GK,Orlando Mosquera,1994-12-25,31,47,0,Al-Fayha,...,8.0,0.0,0.0,0.0,0.0,1.0,PAN,350000.0,Goalkeeper,C
921,1242,Panama,23,DF,Michael Amir Murillo,1996-02-11,30,93,9,Beşiktaş,...,14.0,2.0,29.0,6.0,8.0,0.0,PAN,7000000.0,Right-Back,B
922,1243,Panama,24,FW,Azarias Londoño,2001-06-21,24,10,0,Universidad Católica,...,NaN,NaN,NaN,NaN,NaN,0.0,PAN,175000.0,Centre-Forward,B

In [869]:
df_jugadores_limpia.isna().sum()[df_jugadores_limpia.isna().sum()>0].sort_values() # Cantidad de valores faltantes por variable

misc_performance_crdr              1
misc_performance_2crdy             1
misc_90s                           1
misc_performance_og                1
misc_performance_crdy              1
standard_playing_time_mp           2
standard_playing_time_min          2
standard_playing_time_starts       2
standard_performance_crdr          2
standard_performance_pk            2
standard_performance_pkatt         2
standard_playing_time_90s          2
standard_performance_ast           2
standard_performance_gls           2
standard_performance_gpa           2
standard_performance_g-pk          2
standard_performance_crdy          2
standard_per_90_minutes_gpa        2
standard_per_90_minutes_gls        2
standard_per_90_minutes_ast        2
standard_per_90_minutes_gpa-pk     2
standard_per_90_minutes_g-pk       2
nation_fbref                       3
nat3                               3
posicion_tm                        6
valor_mercado_eur                 14
misc_performance_fld              34
misc_performance_fls              34
misc_performance_tklw             34
misc_performance_int              34
misc_performance_crs              34
misc_performance_off              34
dtype: int64

In [870]:
# Reemplazo los NA en misc_ y standard_ por 0, pues son variables que miden cantidades o proporciones, y el NA puede ser interpretado como 0.
variables_misc_performance = [col for col in df_jugadores_limpia.columns if col.startswith("misc_")]
variables_standard = [col for col in df_jugadores_limpia.columns if col.startswith("standard_")]
df_jugadores_limpia.fillna({col: 0 for col in variables_misc_performance + variables_standard}, inplace=True)
df_jugadores_limpia.isna().sum()[df_jugadores_limpia.isna().sum()>0].sort_values() # Cantidad de valores faltantes por variable

nation_fbref          3
nat3                  3
posicion_tm           6
valor_mercado_eur    14
dtype: int64

In [871]:
# Veo en qué jugadores faltan los valores de nation_fbref, nat3 y posicion_tm
df_jugadores_limpia[df_jugadores_limpia[["nation_fbref", "nat3", "posicion_tm"]].isna().sum(axis=1)>0][["seleccion", "posicion", "cod_fifa", "nation_fbref", "nat3", "posicion_tm"]]

        seleccion posicion cod_fifa nation_fbref nat3       posicion_tm
73    South Korea       MF      KOR          KOR  KOR               NaN
86    South Korea       MF      KOR          NaN  NaN  Central Midfield
171        Brazil       FW      BRA          BRA  BRA               NaN
253      Paraguay       MF      PAR          PAR  PAR               NaN
504         Egypt       DF      EGY          NaN  NaN       Centre-Back
524          Iran       FW      IRN          NaN  NaN    Centre-Forward
572  Saudi Arabia       MF      KSA          KSA  KSA               NaN
737     Argentina       MF      ARG          ARG  ARG               NaN
771        Jordan       FW      JOR          JOR  JOR               NaN

In [872]:
# Relleno los valores faltantes copiando de otras variables
df_jugadores_limpia.fillna({col : df_jugadores_limpia["cod_fifa"] for col in ["nation_fbref", "nat3"]}, inplace=True)

# Reemplazo en posicion_tm por central Midfield si posicion es MF, y sino por Centre-Forward
df_jugadores_limpia["posicion_tm"] = df_jugadores_limpia["posicion_tm"].fillna(df_jugadores_limpia.apply(lambda row: "Central Midfield" if row["posicion"] == "MF" else "Centre-Forward", axis=1))

# Reemplazo los valores faltantes en valor_mercado_eur por el promedio de esta variable.
df_jugadores_limpia.fillna({"valor_mercado_eur" : df_jugadores_limpia["valor_mercado_eur"].mean()}, inplace=True)

df_jugadores_limpia.isna().sum()[df_jugadores_limpia.isna().sum()>0].sort_values() # Cantidad de valores faltantes por variable

Series([], dtype: int64)

In [873]:
df_jugadores_limpia

,player_id,seleccion,numero,posicion,jugador,fecha_nac,edad,caps,goles_seleccion,club,...,misc_performance_fld,misc_performance_off,misc_performance_crs,misc_performance_int,misc_performance_tklw,misc_performance_og,nat3,valor_mercado_eur,posicion_tm,rango_etario
0,1,Czech Republic,1,GK,Matěj Kovář,2000-05-17,26,19,0,PSV Eindhoven,...,5.0,0.0,0.0,1.0,0.0,0.0,CZE,7000000.0,Goalkeeper,B
1,2,Czech Republic,2,DF,David Zima,2000-11-08,25,24,1,Slavia Prague,...,22.0,0.0,4.0,40.0,17.0,0.0,CZE,4500000.0,Centre-Back,B
2,3,Czech Republic,3,DF,Tomáš Holeš,1993-03-31,33,40,2,Slavia Prague,...,28.0,1.0,22.0,44.0,24.0,0.0,CZE,2200000.0,Centre-Back,C
3,4,Czech Republic,4,DF,Robin Hranáč,2000-01-29,26,13,1,TSG Hoffenheim,...,10.0,0.0,6.0,20.0,15.0,0.0,CZE,5500000.0,Centre-Back,B
4,5,Czech Republic,5,DF,Vladimír Coufal,1992-08-22,33,61,2,TSG Hoffenheim,...,42.0,1.0,209.0,39.0,35.0,0.0,CZE,7000000.0,Right-Back,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,1239,Panama,20,MF,Aníbal Godoy,1990-02-10,36,159,4,San Diego FC,...,37.0,0.0,3.0,16.0,14.0,0.0,PAN,200000.0,Defensive Midfield,C
919,1240,Panama,21,MF,César Yanis,1996-01-28,30,56,5,Cobresal,...,36.0,4.0,39.0,24.0,13.0,0.0,PAN,250000.0,Right Winger,B
920,1241,Panama,22,GK,Orlando Mosquera,1994-12-25,31,47,0,Al-Fayha,...,8.0,0.0,0.0,0.0,0.0,1.0,PAN,350000.0,Goalkeeper,C
921,1242,Panama,23,DF,Michael Amir Murillo,1996-02-11,30,93,9,Beşiktaş,...,14.0,2.0,29.0,6.0,8.0,0.0,PAN,7000000.0,Right-Back,B
922,1243,Panama,24,FW,Azarias Londoño,2001-06-21,24,10,0,Universidad Católica,...,0.0,0.0,0.0,0.0,0.0,0.0,PAN,175000.0,Centre-Forward,B

## 7.

In [876]:
selecciones_a_eliminar = df_jugadores_limpia["seleccion"].value_counts()[df_jugadores_limpia["seleccion"].value_counts()<=4].index
jugadores_a_eliminar = df_jugadores_limpia[df_jugadores_limpia["seleccion"].isin(selecciones_a_eliminar)].index
df_jugadores_limpia.drop(index=jugadores_a_eliminar, inplace=True) # Elimino los jugadores de las selecciones con 4 o menos jugadores
df_jugadores_limpia.reset_index(drop=True, inplace=True)

In [877]:
variables_numericas = df_jugadores_limpia.select_dtypes(include='number').drop(columns=["player_id", "numero"])
variables_numericas["seleccion"] = df_jugadores_limpia["seleccion"]
variables_numericas_seleccion_promedio = variables_numericas.groupby("seleccion").mean()
df_selecciones = variables_numericas_seleccion_promedio.reset_index()
df_selecciones

,seleccion,edad,caps,goles_seleccion,standard_playing_time_mp,standard_playing_time_starts,standard_playing_time_min,standard_playing_time_90s,standard_performance_gls,standard_performance_ast,...,misc_performance_crdr,misc_performance_2crdy,misc_performance_fls,misc_performance_fld,misc_performance_off,misc_performance_crs,misc_performance_int,misc_performance_tklw,misc_performance_og,valor_mercado_eur
0,Algeria,26.875000,41.375000,6.500000,24.937500,20.312500,1780.875000,19.768750,3.812500,3.062500,...,0.125000,0.000000,19.437500,20.687500,3.625000,54.312500,16.437500,17.750000,0.000000,1.072500e+07
1,Argentina,29.083333,50.541667,9.041667,24.375000,20.416667,1805.625000,20.070833,3.916667,2.833333,...,0.375000,0.083333,18.333333,25.166667,2.166667,33.875000,13.750000,16.916667,0.125000,3.032051e+07
2,Australia,26.850000,25.800000,2.100000,21.950000,18.150000,1637.150000,18.185000,1.100000,0.900000,...,0.050000,0.050000,15.100000,17.700000,1.150000,25.300000,14.100000,16.950000,0.000000,1.927500e+06
3,Austria,27.869565,37.260870,4.391304,25.478261,20.260870,1800.478261,20.000000,1.956522,2.000000,...,0.173913,0.043478,16.043478,17.739130,1.521739,22.565217,16.130435,18.695652,0.043478,1.199130e+07
4,Belgium,27.115385,41.000000,8.038462,28.192308,23.923077,2124.115385,23.596154,2.500000,2.615385,...,0.076923,0.038462,19.307692,22.653846,2.269231,35.500000,16.615385,19.230769,0.076923,1.982692e+07
5,Bosnia and Herzegovina,25.733333,28.066667,6.000000,24.733333,19.066667,1684.066667,18.706667,3.533333,2.400000,...,0.200000,0.133333,20.666667,19.533333,3.466667,32.866667,12.000000,14.933333,0.200000,6.999485e+06
6,Brazil,28.652174,37.913043,6.391304,25.565217,22.956522,2013.043478,22.373913,5.173913,2.000000,...,0.521739,0.304348,24.130435,27.260870,3.347826,30.043478,12.565217,15.782609,0.043478,4.057792e+07
7,Canada,27.000000,41.142857,6.047619,20.000000,14.047619,1260.047619,13.990476,2.142857,1.380952,...,0.238095,0.142857,14.095238,19.428571,3.476190,10.238095,8.571429,10.142857,0.000000,8.711905e+06
8,Cape Verde,27.750000,29.166667,3.500000,18.833333,12.166667,1084.916667,12.050000,1.333333,1.500000,...,0.250000,0.083333,15.833333,20.583333,1.833333,33.500000,7.916667,14.750000,0.000000,2.381250e+06
9,Colombia,29.952381,44.714286,4.619048,25.523810,21.714286,1914.428571,21.280952,3.285714,2.428571,...,0.190476,0.095238,24.095238,26.190476,3.428571,31.571429,14.523810,19.904762,0.142857,1.214286e+07
10,Croatia,28.083333,47.291667,6.250000,27.208333,21.708333,1927.333333,21.404167,5.000000,2.291667,...,0.083333,0.000000,22.833333,17.625000,3.291667,29.583333,16.333333,14.291667,0.083333,1.320833e+07
11,Curacao,26.545455,17.636364,2.000000,23.636364,17.181818,1540.818182,17.118182,1.000000,1.727273,...,0.272727,0.181818,16.636364,14.727273,2.000000,24.636364,18.636364,18.454545,0.090909,3.153843e+06
12,Czech Republic,27.230769,27.000000,3.653846,25.576923,21.461538,1900.807692,21.126923,4.692308,2.730769,...,0.230769,0.038462,20.384615,23.461538,2.769231,38.269231,16.269231,13.576923,0.076923,6.541346e+06
13,DR Congo,28.764706,34.588235,3.647059,19.588235,13.764706,1273.352941,14.141176,0.823529,0.411765,...,0.117647,0.058824,11.411765,9.000000,1.647059,9.941176,9.705882,8.882353,0.117647,5.835294e+06
14,Ecuador,25.347826,28.739130,3.521739,23.478261,18.347826,1645.565217,18.291304,2.000000,0.913043,...,0.304348,0.043478,17.347826,17.434783,1.869565,14.391304,13.217391,15.304348,0.043478,1.140870e+07
15,Egypt,27.200000,44.800000,16.800000,19.200000,11.800000,1083.000000,12.040000,2.600000,2.800000,...,0.000000,0.000000,9.400000,15.200000,4.800000,48.400000,3.000000,10.800000,0.000000,2.490000e+07
16,England,26.840000,31.840000,5.800000,28.640000,24.080000,2149.760000,23.880000,5.960000,2.560000,...,0.120000,0.040000,20.360000,26.640000,5.320000,46.920000,13.520000,17.280000,0.000000,4.910000e+07
17,France,26.576923,30.153846,3.730769,29.923077,25.730769,2275.807692,25.280769,4.961538,3.500000,...,0.115385,0.076923,22.230769,24.961538,4.769231,33.961538,16.192308,18.692308,0.038462,4.796154e+07
18,Germany,27.538462,31.807692,3.923077,27.923077,24.038462,2120.269231,23.553846,4.346154,3.230769,...,0.038462,0.000000,18.000000,17.807692,3.269231,45.653846,15.115385,19.115385,0.038462,3.521154e+07
19,Ghana,25.500000,18.944444,1.555556,24.222222,19.722222,1740.666667,19.338889,1.444444,1.722222,...,0.055556,0.000000,25.611111,20.500000,3.833333,22.333333,15.722222,19.222222,0.055556,7.297222e+06
20,Haiti,27.714286,28.000000,7.642857,20.214286,12.928571,1180.785714,13.128571,1.285714,0.928571,...,0.071429,0.071429,14.214286,11.357143,1.571429,14.142857,11.428571,11.357143,0.000000,4.117857e+06
21,Iran,29.777778,45.277778,6.333333,20.166667,17.444444,1550.666667,17.222222,2.111111,1.666667,...,0.000000,0.000000,2.444444,2.555556,1.055556,2.555556,0.555556,0.944444,0.000000,1.381944e+06
22,Iraq,23.625000,23.250000,1.500000,21.625000,16.125000,1442.750000,16.025000,2.625000,1.125000,...,0.250000,0.125000,24.250000,24.375000,2.875000,43.750000,14.125000,15.625000,0.000000,1.106250e+06
23,Ivory Coast,24.958333,24.541667,3.208333,23.375000,18.958333,1677.666667,18.645833,3.125000,2.666667,...,0.041667,0.000000,20.916667,20.041667,4.500000,28.708333,11.083333,14.416667,0.000000,1.579519e+07
24,Japan,27.280000,33.200000,3.960000,26.520000,22.120000,1956.920000,21.744000,3.600000,1.920000,...,0.080000,0.000000,17.600000,18.480000,3.840000,26.480000,15.800000,15.520000,0.080000,9.126000e+06
25,Mexico,26.619048,43.285714,4.904762,23.380952,19.952381,1724.619048,19.166667,4.523810,2.000000,...,0.047619,0.000000,17.666667,19.428571,4.714286,19.095238,12.190476,16.142857,0.000000,7.971429e+06
26,Morocco,25.000000,30.227273,4.136364,23.227273,17.818182,1587.454545,17.631818,3.363636,2.272727,...,0.136364,0.000000,17.318182,20.727273,2.045455,24.090909,12.681818,16.045455,0.045455,1.918182e+07
27,Netherlands,27.080000,29.640000,3.840000,27.920000,23.440000,2082.240000,23.136000,3.600000,1.840000,...,0.120000,0.080000,21.960000,21.400000,4.280000,21.280000,13.400000,15.440000,0.080000,3.046800e+07
28,New Zealand,28.687500,31.562500,4.687500,22.437500,20.000000,1731.562500,19.237500,2.500000,2.187500,...,0.000000,0.000000,15.812500,16.312500,1.625000,36.000000,17.500000,18.187500,0.125000,9.109375e+05
29,Norway,26.409091,31.954545,5.409091,24.863636,20.181818,1770.136364,19.663636,4.181818,3.181818,...,0.090909,0.000000,19.590909,20.227273,1.818182,44.909091,11.636364,16.954545,0.090909,2.446364e+07
30,Panama,29.923077,62.769231,6.307692,25.692308,20.230769,1827.307692,20.300000,3.615385,2.923077,...,0.000000,0.000000,14.769231,19.384615,3.384615,27.615385,8.384615,8.923077,0.076923,1.528846e+06
31,Paraguay,27.950000,28.800000,2.150000,23.900000,18.500000,1645.000000,18.280000,2.950000,1.750000,...,0.100000,0.000000,22.100000,18.300000,3.900000,16.950000,14.400000,16.400000,0.100000,7.504227e+06
32,Portugal,27.538462,43.038462,9.807692,29.576923,25.961538,2273.923077,25.265385,5.230769,4.192308,...,0.153846,0.076923,19.961538,23.346154,4.615385,56.269231,14.615385,18.692308,0.076923,3.615385e+07
33,Saudi Arabia,27.782609,34.130435,3.869565,25.304348,17.130435,1540.347826,17.121739,2.478261,2.478261,...,0.391304,0.043478,21.130435,14.478261,2.826087,27.000000,16.956522,21.565217,0.043478,1.921403e+06
34,Scotland,28.111111,38.000000,4.166667,20.611111,15.333333,1367.055556,15.194444,2.888889,1.222222,...,0.277778,0.055556,15.444444,19.166667,2.111111,23.944444,9.111111,12.000000,0.111111,1.043333e+07
35,Senegal,26.666667,39.250000,5.291667,24.041667,18.916667,1704.250000,18.945833,3.000000,1.708333,...,0.208333,0.041667,18.541667,21.333333,4.166667,24.083333,13.250000,14.541667,0.000000,1.304167e+07
36,South Africa,26.520000,18.280000,2.400000,22.960000,18.120000,1641.920000,18.244000,2.360000,1.600000,...,0.240000,0.120000,17.040000,16.360000,3.720000,25.480000,13.040000,17.760000,0.000000,2.515382e+06
37,South Korea,28.750000,51.562500,8.375000,20.750000,16.562500,1458.625000,16.206250,2.000000,1.375000,...,0.125000,0.000000,13.062500,11.625000,2.937500,20.687500,8.625000,8.312500,0.000000,1.135577e+07
38,Spain,26.166667,26.916667,4.333333,29.541667,25.416667,2226.583333,24.733333,4.458333,2.875000,...,0.125000,0.083333,21.083333,25.083333,4.791667,40.875000,15.333333,20.416667,0.000000,5.295833e+07
39,Sweden,26.388889,24.055556,3.333333,25.388889,18.611111,1679.222222,18.666667,2.833333,1.444444,...,0.277778,0.222222,21.500000,19.944444,1.166667,32.722222,14.277778,16.944444,0.166667,1.655556e+07
40,Switzerland,27.760000,43.880000,4.720000,27.000000,23.160000,2029.640000,22.552000,2.640000,2.040000,...,0.200000,0.000000,20.040000,21.080000,2.160000,30.680000,17.360000,18.120000,0.120000,1.187800e+07
41,Tunisia,26.500000,28.928571,2.071429,20.142857,15.500000,1357.714286,15.078571,1.357143,1.500000,...,0.214286,0.214286,17.500000,18.500000,1.285714,23.000000,13.714286,12.785714,0.000000,3.914286e+06
42,Turkey,26.956522,37.217391,3.739130,23.652174,17.652174,1547.478261,17.200000,3.478261,3.000000,...,0.130435,0.000000,18.347826,19.478261,1.956522,46.521739,9.869565,14.782609,0.000000,1.486087e+07
43,United States,26.565217,37.608696,4.652174,27.260870,23.391304,2070.043478,23.000000,3.260870,2.260870,...,0.217391,0.000000,20.565217,20.304348,2.826087,32.521739,18.391304,20.521739,0.086957,1.298478e+07
44,Uruguay,28.080000,33.360000,2.640000,22.960000,18.520000,1629.120000,18.104000,3.600000,2.400000,...,0.280000,0.040000,17.800000,21.600000,2.400000,34.800000,12.560000,18.080000,0.160000,2.098800e+07
45,Uzbekistan,28.500000,60.333333,15.166667,16.000000,13.000000,1182.666667,13.150000,4.833333,1.166667,...,0.166667,0.000000,5.833333,4.000000,1.333333,3.666667,5.500000,6.166667,0.166667,3.633333e+06